### PR TITLE
fix reversed naming convention

### PR DESCRIPTION
**Pull request by ThePlexus**

### CODE REVIEW

**Comment by ThePlexus** [comment]
putting it onto the correct branch this time.

**Comment by merge** [comment]
thanks, but I'm afraid you're in the wrong repo. this is a (development-)fork of heads which is upstream at https://github.com/osresearch/heads where the issue seems to be fixed already.

**Comment by ThePlexus** [comment]
Cheers @merge  yes am working from your CB4.11 branch for the p8h61-m_pro . the TPM patch i put in wasnt present till 4.10 and the board itself until 4.9. So this is why im dabbling on this branch. forgive the intrusion ;)

**Comment by merge** [comment]
haha, np :)

**Pull request closed without merging**
